const DATA=window.EXAM_WORDS||[];
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const UNITS=[...new Map(DATA.map(x=>[x.unit,{unit:x.unit,title:x.title}])).values()];
const KEY='wordloom-60-v2';
let saved=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}})();
saved.vocabAnswers=saved.vocabAnswers||0;saved.practiceAnswers=saved.practiceAnswers||0;saved.seen=saved.seen||{};saved.mastered=saved.mastered||{};saved.mistakes=saved.mistakes||{};
const persist=()=>{localStorage.setItem(KEY,JSON.stringify(saved));updateStats()};
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const norm=s=>String(s||'').trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ');
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function blank(sentence,word,reveal=''){const i=sentence.toLowerCase().indexOf(word.toLowerCase());if(i<0)return esc(sentence);return esc(sentence.slice(0,i))+`<span class="blank">${esc(reveal||'________')}</span>`+esc(sentence.slice(i+word.length))}
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
function options(all='全部单元'){return `<option value="all">${all}</option>`+UNITS.map(x=>`<option value="${x.unit}">${x.unit} · ${x.title}</option>`).join('')}
function go(name){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));

function updateStats(){const mastered=Object.keys(saved.mastered).filter(id=>saved.mastered[id]).length,mistakes=Object.keys(saved.mistakes).filter(id=>saved.mistakes[id]>0).length,seen=Object.keys(saved.seen).length,pct=Math.round(seen/DATA.length*100);$('#stat-vocab').textContent=saved.vocabAnswers;$('#stat-practice').textContent=saved.practiceAnswers;$('#stat-mastered').textContent=mastered;$('#stat-mistakes').textContent=mistakes;$('#home-meter').style.width=pct+'%';$('#home-progress').textContent=`总进度 ${pct}%`;renderUnits()}
function renderUnits(){$('#unit-grid').innerHTML=UNITS.map(u=>{const items=DATA.filter(x=>x.unit===u.unit),done=items.filter(x=>saved.mastered[x.id]).length;return `<button class="unit-card" data-unit="${u.unit}"><small>${u.unit.toUpperCase()}</small><h3>${u.title}</h3><p>${done} / 10 词已掌握</p><i style="width:${done*10}%"></i></button>`}).join('');$$('.unit-card').forEach(b=>b.onclick=()=>{$('#vocab-unit').value=b.dataset.unit;resetVocab();go('vocab')})}

// Part 1: four-choice meaning practice
$('#vocab-unit').innerHTML=options();let vocabPool=[],vocabIndex=0,vocabRight=0,vocabTotal=0,vocabAnswered=false;
function resetVocab(){const unit=$('#vocab-unit').value;vocabPool=shuffle(unit==='all'?DATA:DATA.filter(x=>x.unit===unit));vocabIndex=0;vocabRight=0;vocabTotal=0;renderVocab()}
function distractors(item){let pool=DATA.filter(x=>x.id!==item.id&&x.meaning!==item.meaning);let same=shuffle(pool.filter(x=>x.unit===item.unit));let chosen=same.slice(0,3);if(chosen.length<3)chosen.push(...shuffle(pool.filter(x=>!chosen.includes(x))).slice(0,3-chosen.length));return shuffle([item,...chosen])}
function renderVocab(){if(!vocabPool.length)return;const q=vocabPool[vocabIndex%vocabPool.length];vocabAnswered=false;$('#vocab-count').textContent=`第 ${vocabIndex+1} 题 · 共 ${vocabPool.length} 词`;$('#vocab-score').textContent=`${vocabRight} / ${vocabTotal}`;$('#vocab-unit-label').textContent=`${q.unit} · ${q.title}`;$('#vocab-word').textContent=q.word;$('#vocab-feedback').className='feedback';$('#vocab-feedback').textContent='';$('#vocab-next').hidden=true;$('#vocab-choices').innerHTML=distractors(q).map((x,i)=>`<button class="choice" data-id="${x.id}"><b>${String.fromCharCode(65+i)}</b>${esc(x.meaning)}</button>`).join('');$$('.choice').forEach(b=>b.onclick=()=>answerVocab(q,b))}
function answerVocab(q,button){if(vocabAnswered)return;vocabAnswered=true;vocabTotal++;saved.vocabAnswers++;saved.seen[q.id]=1;const ok=button.dataset.id===q.id;if(ok){vocabRight++;saved.mastered[q.id]=1;saved.mistakes[q.id]=Math.max(0,(saved.mistakes[q.id]||0)-1)}else{saved.mistakes[q.id]=(saved.mistakes[q.id]||0)+1}persist();$$('.choice').forEach(b=>{b.disabled=true;if(b.dataset.id===q.id)b.classList.add('correct');else if(b===button)b.classList.add('wrong')});$('#vocab-score').textContent=`${vocabRight} / ${vocabTotal}`;const f=$('#vocab-feedback');f.className='feedback '+(ok?'good':'bad');f.innerHTML=`${ok?'回答正确。':'正确含义：<strong>'+esc(q.meaning)+'</strong>。'}<br>${esc(q.sentence)}<br><small>${esc(q.chinese)}</small>`;$('#vocab-next').hidden=false}
$('#vocab-next').onclick=()=>{vocabIndex++;renderVocab()};$('#vocab-unit').onchange=resetVocab;$('#speak-word').onclick=()=>speak(vocabPool[vocabIndex%vocabPool.length].word);

// Part 2: exact exam-style sentence practice
$('#practice-unit').innerHTML=options();let practicePool=[],practiceIndex=0,practiceRight=0,practiceTotal=0,streak=0,current=null,practiceAnswered=false;
function resetPractice(){const unit=$('#practice-unit').value,only=$('#mistakes-only').checked;practicePool=shuffle(DATA.filter(x=>(unit==='all'||x.unit===unit)&&(!only||saved.mistakes[x.id]>0)));practiceIndex=0;practiceRight=0;practiceTotal=0;streak=0;renderPractice()}
function renderPractice(){if(!practicePool.length){$('#practice-count').textContent='没有符合条件的题目';$('#practice-sentence').textContent='';$('#practice-chinese').textContent=$('#mistakes-only').checked?'当前范围还没有错题。':'当前范围没有题目。';$('#practice-form').hidden=true;return}$('#practice-form').hidden=false;current=practicePool[practiceIndex%practicePool.length];practiceAnswered=false;$('#practice-count').textContent=`第 ${practiceIndex+1} 题 · ${current.unit}`;$('#practice-score').textContent=`${practiceRight} / ${practiceTotal}`;$('#practice-streak').textContent=streak;$('#practice-sentence').innerHTML=blank(current.sentence,current.word);$('#practice-chinese').textContent=current.chinese;$('#practice-hint').textContent=current.hint;$('#practice-note').textContent=current.note?`（${current.note}）`:`请变为句中所需形式`;$('#practice-input').value='';$('#practice-input').disabled=false;$('#practice-form button').disabled=false;$('#practice-feedback').className='feedback';$('#practice-feedback').textContent='';$('#practice-next').hidden=true;setTimeout(()=>$('#practice-input').focus(),80)}
$('#practice-form').onsubmit=e=>{e.preventDefault();if(practiceAnswered)return;const raw=$('#practice-input').value;if(!raw.trim())return;practiceAnswered=true;practiceTotal++;saved.practiceAnswers++;saved.seen[current.id]=1;const ok=norm(raw)===norm(current.word);if(ok){practiceRight++;streak++;saved.mastered[current.id]=1;saved.mistakes[current.id]=Math.max(0,(saved.mistakes[current.id]||0)-1)}else{streak=0;saved.mistakes[current.id]=(saved.mistakes[current.id]||0)+1}persist();$('#practice-score').textContent=`${practiceRight} / ${practiceTotal}`;$('#practice-streak').textContent=streak;$('#practice-input').disabled=true;$('#practice-form button').disabled=true;$('#practice-sentence').innerHTML=blank(current.sentence,current.word,current.word);const f=$('#practice-feedback');f.className='feedback '+(ok?'good':'bad');f.innerHTML=ok?`正确：<strong>${esc(current.hint)} → ${esc(current.word)}</strong>`:`正确答案是 <strong>${esc(current.word)}</strong>。你的答案：${esc(raw)}<br><small>${esc(current.hint)} → ${esc(current.word)}</small>`;$('#practice-next').hidden=false};
$('#practice-next').onclick=()=>{practiceIndex++;renderPractice()};$('#practice-unit').onchange=resetPractice;$('#mistakes-only').onchange=resetPractice;

// Mock exam
$('#mock-unit').innerHTML=options('全部单元混合');let minutes=8,mockItems=[],timer=null,seconds=0,submitted=false;
$$('[data-minutes]').forEach(b=>b.onclick=()=>{$$('[data-minutes]').forEach(x=>x.classList.remove('active'));b.classList.add('active');minutes=Number(b.dataset.minutes)});
function startMock(){const unit=$('#mock-unit').value,pool=unit==='all'?DATA:DATA.filter(x=>x.unit===unit);mockItems=shuffle(pool).slice(0,10);submitted=false;$('#mock-setup').hidden=true;$('#mock-result').hidden=true;$('#mock-paper').hidden=false;$('#mock-questions').innerHTML=mockItems.map((q,i)=>`<section class="mock-question"><small>${String(i+1).padStart(2,'0')} · ${q.unit} · ${esc(q.meaning)}</small><p class="mock-en">${blank(q.sentence,q.word)}</p><p>${esc(q.chinese)}</p><input name="q${i}" autocomplete="off" spellcheck="false" aria-label="第${i+1}题答案"></section>`).join('');seconds=minutes*60;updateTimer();clearInterval(timer);if(minutes)timer=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timer);submitMock()}},1000);scrollTo({top:0,behavior:'smooth'})}
function updateTimer(){if(!minutes){$('#mock-timer').textContent='不限时';return}const m=Math.floor(seconds/60),s=seconds%60;$('#mock-timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function submitMock(e){if(e)e.preventDefault();if(submitted)return;submitted=true;clearInterval(timer);const fd=new FormData($('#mock-form'));let right=0;const rows=mockItems.map((q,i)=>{const raw=String(fd.get('q'+i)||''),ok=norm(raw)===norm(q.word);if(ok)right++;saved.seen[q.id]=1;if(ok){saved.mastered[q.id]=1;saved.mistakes[q.id]=Math.max(0,(saved.mistakes[q.id]||0)-1)}else saved.mistakes[q.id]=(saved.mistakes[q.id]||0)+1;return `<article class="result-row ${ok?'good':'bad'}"><small>${i+1}. ${q.unit}</small><p>${blank(q.sentence,q.word,q.word)}</p><strong>${ok?'✓ 正确':'✕ 你的答案：'+esc(raw||'（未作答）')}</strong>${ok?'':`<p>正确答案：<b>${esc(q.word)}</b>　提示词：${esc(q.hint)}</p>`}</article>`}).join('');persist();$('#mock-paper').hidden=true;const r=$('#mock-result');r.hidden=false;r.innerHTML=`<div class="result-head"><p class="eyebrow pale">RESULT</p><strong>${right*10}</strong><span>${right} / 10 题正确</span><p><button class="primary" id="retry">再考一套</button></p></div><div class="result-list">${rows}</div>`;$('#retry').onclick=()=>{$('#mock-result').hidden=true;$('#mock-setup').hidden=false};scrollTo({top:0,behavior:'smooth'})}
$('#start-mock').onclick=startMock;$('#mock-form').onsubmit=submitMock;

updateStats();resetVocab();resetPractice();
