window.EXAM_WORDS = [
  {
    "id": "u1-01",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 1,
    "word": "estranged",
    "meaning": "疏远的；感到陌生的",
    "sentence": "Millions of Americans must feel estranged from their own faces.",
    "chinese": "数百万美国人一定会对自己的面孔感到陌生。",
    "hint": "estrange",
    "note": ""
  },
  {
    "id": "u1-02",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 2,
    "word": "devoid",
    "meaning": "缺乏的；没有的",
    "sentence": "And although I am in most respects devoid of Asian characteristics, I do have an Asian face.",
    "chinese": "尽管我在大多数方面都不具备亚洲人的特征，但我的确长着一张亚洲人的脸。",
    "hint": "void",
    "note": ""
  },
  {
    "id": "u1-03",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 3,
    "word": "conspicuous",
    "meaning": "显眼的；引人注目的",
    "sentence": "A conspicuous person standing apart from the crowd and yet devoid of any individuality.",
    "chinese": "一个在人群中格外显眼、与众人分离，却又毫无个性的人。",
    "hint": "conspicuously",
    "note": ""
  },
  {
    "id": "u1-04",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 4,
    "word": "patronizes",
    "meaning": "以高人一等的态度对待；屈尊俯就",
    "sentence": "An icon of so much that the culture pretends to honor but that it in fact patronizes and exploits.",
    "chinese": "他象征着许多这种文化表面上假装尊重、实际上却以高人一等的态度对待并加以利用的东西。",
    "hint": "patronize",
    "note": ""
  },
  {
    "id": "u1-05",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 5,
    "word": "ratify",
    "meaning": "证实；认可",
    "sentence": "Asian American success is typically taken to ratify the American Dream and to prove that minorities can make it in this country without handouts.",
    "chinese": "亚裔美国人的成功通常被用来证实美国梦，并证明少数族裔即使不依靠救济，也能够在这个国家取得成功。",
    "hint": "ratification",
    "note": ""
  },
  {
    "id": "u1-06",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 6,
    "word": "incited",
    "meaning": "引发；煽动",
    "sentence": "Earlier this year, the publication of Amy Chua’s Battle Hymn of the Tiger Mother incited a collective airing out of many varieties of race-based hysteria.",
    "chinese": "今年早些时候，蔡美儿的《虎妈战歌》出版后，引发了人们集体宣泄各种以种族为基础的歇斯底里情绪。",
    "hint": "incite",
    "note": ""
  },
  {
    "id": "u1-07",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 7,
    "word": "meritocracy",
    "meaning": "择优制度；精英管理制度",
    "sentence": "Here we have something like pure meritocracy.",
    "chinese": "在这里，我们看到的是一种近乎纯粹的择优制度。",
    "hint": "meritocratic",
    "note": ""
  },
  {
    "id": "u1-08",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 8,
    "word": "wariness",
    "meaning": "警惕；戒备",
    "sentence": "A couple of years ago, she revisited this issue in her senior thesis at Harvard, where she interviewed graduates of elite public schools and found that the white students regarded the Asian students with wariness.",
    "chinese": "几年前，她在哈佛大学的毕业论文中再次探讨了这个问题；她采访了精英公立学校的毕业生，并发现白人学生对亚裔学生抱有戒备心理。",
    "hint": "wary",
    "note": ""
  },
  {
    "id": "u1-09",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 9,
    "word": "insidious",
    "meaning": "隐蔽而有害的；潜伏的",
    "sentence": "Part of the insidious nature of the “bamboo ceiling” is that it does not seem to be caused by overt racism.",
    "chinese": "“竹子天花板”的隐蔽危害之一在于，它看起来并不是由公开的种族主义造成的。",
    "hint": "insidiously",
    "note": ""
  },
  {
    "id": "u1-10",
    "unit": "Unit 1",
    "title": "Paper Tigers",
    "number": 10,
    "word": "defiance",
    "meaning": "反抗；蔑视；不屈",
    "sentence": "There is something salutary in that proud defiance.",
    "chinese": "这种骄傲而不屈的反抗中，包含着某种有益的力量。",
    "hint": "defiant",
    "note": ""
  },
  {
    "id": "u2-01",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 1,
    "word": "reinstated",
    "meaning": "恢复；重新安装",
    "sentence": "One morning, of course, the job was all finished, the well capped, the pump reinstated, the fresh water marvelled at.",
    "chinese": "一天早晨，工程终于全部完成了：井口封好了，水泵重新安装了，清新的井水也令人赞叹不已。",
    "hint": "reinstate",
    "note": ""
  },
  {
    "id": "u2-02",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 2,
    "word": "altered",
    "meaning": "改变；使发生变化",
    "sentence": "How all my own territory would be altered, as if a landslide had gone through it and skimmed off all meaning except loss of Mike.",
    "chinese": "我的整个世界竟会因此而改变，仿佛一场山体滑坡席卷而过，把除失去迈克之外的一切意义都刮去了。",
    "hint": "alter",
    "note": ""
  },
  {
    "id": "u2-03",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 3,
    "word": "dovetailed",
    "meaning": "吻合；衔接得很好",
    "sentence": "Our pregnancies had dovetailed, so that we had managed with one set of maternity clothes.",
    "chinese": "我们的怀孕时期正好前后衔接，因此只用一套孕妇装就应付过去了。",
    "hint": "dovetail",
    "note": ""
  },
  {
    "id": "u2-04",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 4,
    "word": "deprivation",
    "meaning": "匮乏；剥夺",
    "sentence": "And I had moved for the newfangled reason that was approved of only in some special circles—leaving husband and house and all the things acquired during the marriage except, of course, the children, who were to be parcelled about, in the hope of making a life that could be lived without hypocrisy or deprivation or shame.",
    "chinese": "而我搬走则是出于一种只有某些特殊圈子才认可的新潮理由——离开丈夫、房子以及婚姻期间获得的一切，当然孩子除外，孩子将被分别安排照看；我希望由此过上一种没有虚伪、匮乏和羞耻的生活。",
    "hint": "deprive",
    "note": ""
  },
  {
    "id": "u2-05",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 5,
    "word": "scrupulous",
    "meaning": "恪守原则的；谨慎正直的",
    "sentence": "I had the feeling, however, that he was a scrupulous man, he would refrain.",
    "chinese": "然而，我觉得他是一个恪守原则的人，他会克制自己。",
    "hint": "scrupulously",
    "note": ""
  },
  {
    "id": "u2-06",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 6,
    "word": "beguiled",
    "meaning": "吸引；迷住",
    "sentence": "The notion of being a wife beguiled me, just as if I had never been one.",
    "chinese": "做妻子的这个念头使我着迷，仿佛我从来没有做过妻子一样。",
    "hint": "beguile",
    "note": ""
  },
  {
    "id": "u2-07",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 7,
    "word": "impenetrable",
    "meaning": "无法穿透的；难以进入的",
    "sentence": "The bushes right at the edge of the grass looked impenetrable, but close up there were little openings, the narrow paths that animals or people looking for golf balls had made.",
    "chinese": "草地边缘的灌木丛看起来密不透风，但走近后可以看到一些小缺口，那是动物或寻找高尔夫球的人踩出来的狭窄小径。",
    "hint": "penetrate",
    "note": ""
  },
  {
    "id": "u2-08",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 8,
    "word": "restraint",
    "meaning": "克制；约束",
    "sentence": "His touch was still one of restraint more than comfort.",
    "chinese": "他的触碰与其说是在安慰我，不如说是在约束我。",
    "hint": "restrain",
    "note": ""
  },
  {
    "id": "u2-09",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 9,
    "word": "radiance",
    "meaning": "光辉；灿烂",
    "sentence": "Now was the time, when we were soaked and safe and confronted with radiance.",
    "chinese": "现在正是时候：我们浑身湿透，却已安全，并且正面对着灿烂的阳光。",
    "hint": "radiant",
    "note": ""
  },
  {
    "id": "u2-10",
    "unit": "Unit 4",
    "title": "Nettles",
    "number": 10,
    "word": "insignificant",
    "meaning": "微不足道的；不起眼的",
    "sentence": "The stinging nettles that we must have got into are more insignificant plants, with stalks wickedly outfitted with fine, fierce, skin-piercing and inflaming spines.",
    "chinese": "我们一定碰到的刺荨麻其实是更不起眼的植物，它们的茎上恶狠狠地长满了细小、尖锐、能够刺穿皮肤并引起红肿的刺。",
    "hint": "significance",
    "note": ""
  },
  {
    "id": "u3-01",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 1,
    "word": "breached",
    "meaning": "突破；破坏",
    "sentence": "Now, on a planetary scale, this division has been breached.",
    "chinese": "如今，在整个地球的范围内，这种界限已经被打破了。",
    "hint": "breach",
    "note": ""
  },
  {
    "id": "u3-02",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 2,
    "word": "portending",
    "meaning": "预示；预兆",
    "sentence": "Like the Creation, the portending global events are cosmic: They change the relationship between the planet Earth and its star, the sun.",
    "chinese": "这些预示着未来的全球性事件，如同创世一样具有宇宙意义：它们改变了地球与其恒星——太阳——之间的关系。",
    "hint": "portend",
    "note": ""
  },
  {
    "id": "u3-03",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 3,
    "word": "tampering",
    "meaning": "擅自干预；胡乱摆弄",
    "sentence": "We have been tampering with this powerful force, unaware, like the Sorcerer’s Apprentice, of the potentially disastrous consequences of our actions.",
    "chinese": "我们一直在擅自干预这种强大的力量，却像魔法师的学徒一样，没有意识到自己的行为可能带来灾难性的后果。",
    "hint": "tamper",
    "note": ""
  },
  {
    "id": "u3-04",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 4,
    "word": "noxious",
    "meaning": "有毒的；有害的",
    "sentence": "Noxious flames of smog blanket over major cities.",
    "chinese": "有害的烟雾如火焰般笼罩着各大城市。",
    "hint": "noxiously",
    "note": ""
  },
  {
    "id": "u3-05",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 5,
    "word": "instigated",
    "meaning": "引发；挑起",
    "sentence": "The human attack on the ecosphere has instigated an ecological counterattack.",
    "chinese": "人类对生态圈的攻击已经引发了生态系统的反击。",
    "hint": "instigate",
    "note": ""
  },
  {
    "id": "u3-06",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 6,
    "word": "elaborate",
    "meaning": "复杂精密的",
    "sentence": "This expresses the fact that the ecosphere is an elaborate network, in which each component part is linked to many others.",
    "chinese": "这表明生态圈是一个复杂精密的网络，其中每一个组成部分都与许多其他部分相互联系。",
    "hint": "elaborately",
    "note": ""
  },
  {
    "id": "u3-07",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 7,
    "word": "contaminated",
    "meaning": "污染",
    "sentence": "Yields rose, but not in proportion to the rate of fertilizer application; year by year, less and less of the applied fertilizer was taken up by the crop and progressively more drained through the soil into groundwater, in the form of nitrate that contaminated rivers, lakes, and water supplies.",
    "chinese": "产量提高了，但并未与施肥量成正比；一年又一年，作物吸收的肥料越来越少，而越来越多的肥料以硝酸盐的形式穿过土壤渗入地下水，污染了河流、湖泊和供水系统。",
    "hint": "contaminate",
    "note": ""
  },
  {
    "id": "u3-08",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 8,
    "word": "biodegradable",
    "meaning": "可生物降解的",
    "sentence": "Nylon, for example, unlike a natural polymer such as cellulose, is not biodegradable—that is, there is no enzyme in any known living organism that can break it down.",
    "chinese": "例如，尼龙不同于纤维素这样的天然聚合物，它不能被生物降解——也就是说，在任何已知的生物体内都不存在能够分解它的酶。",
    "hint": "biodegrade",
    "note": ""
  },
  {
    "id": "u3-09",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 9,
    "word": "unavoidable",
    "meaning": "不可避免的",
    "sentence": "In contrast, when the debts represented by environmental pollution are created by the technosphere and transferred to the ecosphere, they are never canceled; damage is unavoidable.",
    "chinese": "相比之下，当技术圈制造了由环境污染所代表的债务，并把这些债务转移给生态圈时，它们永远不会被取消；损害是不可避免的。",
    "hint": "avoid",
    "note": ""
  },
  {
    "id": "u3-10",
    "unit": "Unit 5",
    "title": "At War with the Planet",
    "number": 10,
    "word": "mismatch",
    "meaning": "不匹配；不协调",
    "sentence": "What we call the “environmental crisis”—the array of critical unsolved problems ranging from local toxic dumps to the disruption of global climate—is a product of the drastic mismatch between the cyclical, conservative, and self-consistent processes of the ecosphere and the linear, innovative, but ecologically disharmonious processes of the technosphere.",
    "chinese": "我们所谓的“环境危机”——从局部的有毒废物倾倒场到全球气候受到破坏等一系列尚未解决的严重问题——是生态圈循环、保守而自洽的过程与技术圈线性、创新却不符合生态规律的过程之间严重失调的产物。",
    "hint": "mismatched",
    "note": ""
  },
  {
    "id": "u4-01",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 1,
    "word": "perilously",
    "meaning": "危险地",
    "sentence": "Rich and poor have lived together, always uncomfortably and sometimes perilously, since the beginning of time.",
    "chinese": "自古以来，富人和穷人一直共同生活，他们之间的相处始终令人不安，有时甚至充满危险。",
    "hint": "perilous",
    "note": ""
  },
  {
    "id": "u4-02",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 2,
    "word": "affluence",
    "meaning": "富裕；富足",
    "sentence": "And the problems that arise from the continuing coexistence of affluence and poverty—and particularly the process by which good fortune is justified in the presence of the ill fortune of others—have been an intellectual preoccupation for centuries.",
    "chinese": "富裕与贫困长期并存所产生的问题——尤其是人们如何在他人的不幸面前为自己的幸运辩护——几个世纪以来一直是思想界持续关注的问题。",
    "hint": "affluent",
    "note": ""
  },
  {
    "id": "u4-03",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 3,
    "word": "fecundity",
    "meaning": "生育力；多产",
    "sentence": "And it was so because it was a product of their excessive fecundity: their grievously uncontrolled lust caused them to breed up to the full limits of the available subsistence.",
    "chinese": "之所以如此，是因为贫困被认为是穷人过度生育的结果：他们严重失控的欲望使他们不断繁衍，直到达到现有生活资料所能承受的极限。",
    "hint": "fecund",
    "note": ""
  },
  {
    "id": "u4-04",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 4,
    "word": "amelioration",
    "meaning": "改善；缓解",
    "sentence": "Poverty being caused in the bed meant that the rich were not responsible for either its creation or its amelioration.",
    "chinese": "既然贫困被认为产生于床笫之间，那么富人既不必为它的产生负责，也不必为改善它负责。",
    "hint": "ameliorate",
    "note": ""
  },
  {
    "id": "u4-05",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 5,
    "word": "overriding",
    "meaning": "首要的；压倒一切的",
    "sentence": "In economic life, as in biological development, the overriding rule was survival of the fittest.",
    "chinese": "在经济生活中，如同在生物进化中一样，压倒一切的法则是适者生存。",
    "hint": "override",
    "note": ""
  },
  {
    "id": "u4-06",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 6,
    "word": "amorphous",
    "meaning": "模糊不定的；无定形的",
    "sentence": "We passed on to the more amorphous denial of poverty associated with Calvin Coolidge and Herbert Hoover.",
    "chinese": "随后，我们转向了与卡尔文·柯立芝和赫伯特·胡佛有关的、更加模糊不定的贫困否认方式。",
    "hint": "amorphously",
    "note": ""
  },
  {
    "id": "u4-07",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 7,
    "word": "succor",
    "meaning": "救助；援助",
    "sentence": "Being incompetent and ineffective, it must not be asked to succor the poor; it will only louse things up or make things worse.",
    "chinese": "既然政府被认为无能而低效，就不应该要求它去救助穷人；它只会把事情搞砸，或者使情况变得更糟。",
    "hint": "succor",
    "note": "???????"
  },
  {
    "id": "u4-08",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 8,
    "word": "aberrations",
    "meaning": "异常现象；偏差",
    "sentence": "When these aberrations have occurred, they have, oddly enough, all been in the Pentagon.",
    "chinese": "奇怪的是，当这些异常现象出现时，它们全都发生在五角大楼。",
    "hint": "aberrant",
    "note": ""
  },
  {
    "id": "u4-09",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 9,
    "word": "feckless",
    "meaning": "无能而不负责任的",
    "sentence": "They transfer income from the diligent to the idle and feckless, thus reducing the effort of the diligent and encouraging the idleness of the idle.",
    "chinese": "这些措施把收入从勤奋的人转移给懒惰而又不负责任的人，从而削弱勤奋者的努力，并助长懒惰者的惰性。",
    "hint": "fecklessness",
    "note": ""
  },
  {
    "id": "u4-10",
    "unit": "Unit 7",
    "title": "How to Get the Poor off Our Conscience",
    "number": 10,
    "word": "tranquility",
    "meaning": "安宁；平静",
    "sentence": "To the extent that we can make contentment as nearly universal as possible, we will preserve and enlarge the social and political tranquility for which conservatives, above all, should yearn.",
    "chinese": "只要我们能够使满足感尽可能普遍，就能够维护并扩大社会和政治的安宁，而这种安宁尤其应当是保守派所渴望的。",
    "hint": "tranquil",
    "note": ""
  },
  {
    "id": "u5-01",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 1,
    "word": "aspirations",
    "meaning": "愿望；抱负",
    "sentence": "In an epoch dominated by the aspirations of new states for national development, it is instructive to recall that the United States itself began as an underdeveloped country.",
    "chinese": "在一个由新兴国家追求民族发展的愿望所主导的时代，回想美国本身也是从一个欠发达国家起步的，是很有启发意义的。",
    "hint": "aspire",
    "note": ""
  },
  {
    "id": "u5-02",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 2,
    "word": "facilitated",
    "meaning": "促进；使便利",
    "sentence": "Several elements seem fundamental to the philosophy which facilitated the rapid social and economic development of the American continent.",
    "chinese": "有几个因素似乎构成了这样一种思想的基础，而正是这种思想促进了美洲大陆社会和经济的快速发展。",
    "hint": "facilitate",
    "note": ""
  },
  {
    "id": "u5-03",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 3,
    "word": "potentialities",
    "meaning": "潜能；潜力",
    "sentence": "It arose originally from a philosophical rather than an economic commitment—from a faith in the dignity of man and from the resulting belief that it is the responsibility of society to offer man the opportunity to develop his highest potentialities.",
    "chinese": "这种信念最初源于一种哲学承诺，而不是经济承诺——它来自对人的尊严的信仰，以及由此产生的信念，即社会有责任为人提供发展其最高潜能的机会。",
    "hint": "potential",
    "note": ""
  },
  {
    "id": "u5-04",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 4,
    "word": "ideology",
    "meaning": "意识形态",
    "sentence": "By ideology I mean a body of systematic and rigid dogma by which people seek to understand the world—and to preserve or transform it.",
    "chinese": "我所说的意识形态，是指一整套系统而僵化的教条，人们试图借助它来理解世界，并维护或改造世界。",
    "hint": "ideological",
    "note": ""
  },
  {
    "id": "u5-05",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 5,
    "word": "vulnerability",
    "meaning": "易受影响；脆弱性",
    "sentence": "After all, the American mind was conditioned by one of the noblest and most formidable structures of analysis ever devised, Calvinist theology, and any intellect so shaped was bound to have certain vulnerability to secular ideology ever after.",
    "chinese": "毕竟，美国人的思想曾受到人类创造出的最崇高、最强大的分析体系之一——加尔文主义神学——的影响；任何以这种方式塑造出来的思想，此后都必然会在某种程度上容易受到世俗意识形态的影响。",
    "hint": "vulnerable",
    "note": ""
  },
  {
    "id": "u5-06",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 6,
    "word": "pragmatic",
    "meaning": "务实的；实用主义的",
    "sentence": "The most vital American social thought has been empirical, practical, pragmatic.",
    "chinese": "美国最富有生命力的社会思想一直是经验性的、实际的和务实的。",
    "hint": "pragmatically",
    "note": ""
  },
  {
    "id": "u5-07",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 7,
    "word": "salient",
    "meaning": "显著的；突出的",
    "sentence": "An ideology is not a picture of actuality; it is a model derived from actuality, a model designed to isolate certain salient features of actuality which the model builder, the ideologist, regards as of crucial importance.",
    "chinese": "意识形态并不是现实本身的图景；它是从现实中提炼出来的模型，旨在把现实中的某些显著特征分离出来，而模型的建构者——意识形态家——认为这些特征至关重要。",
    "hint": "salience",
    "note": ""
  },
  {
    "id": "u5-08",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 8,
    "word": "repugnant",
    "meaning": "令人反感的；不可接受的",
    "sentence": "The American tradition has found this view of human history repugnant and false.",
    "chinese": "美国传统认为这种人类历史观既令人反感，又是错误的。",
    "hint": "repugnance",
    "note": ""
  },
  {
    "id": "u5-09",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 9,
    "word": "contingency",
    "meaning": "偶然性；不确定性",
    "sentence": "Against the deterministic interpretation of history, against the closed universe, James stood for what he called the unfinished universe—a universe marked by growth, variety, ambiguity, mystery, and contingency.",
    "chinese": "为了反对对历史的决定论解释、反对封闭的宇宙观，詹姆斯主张他所谓的“未完成的宇宙”——一个以成长、多样性、模糊性、神秘性和偶然性为特征的宇宙。",
    "hint": "contingent",
    "note": ""
  },
  {
    "id": "u5-10",
    "unit": "Unit 9",
    "title": "The One Against the Many",
    "number": 10,
    "word": "infallibility",
    "meaning": "绝对正确；不会犯错",
    "sentence": "Their religious and their intellectual heritage join in leading them to suspect fellow men who lay claim to infallibility.",
    "chinese": "他们的宗教传统和思想传统共同使他们对那些自称绝对不会犯错的人保持怀疑。",
    "hint": "infallible",
    "note": ""
  },
  {
    "id": "u6-01",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 1,
    "word": "presentiment",
    "meaning": "预感",
    "sentence": "I had a presentiment, the very first afternoon, that the play would never regain its balance and that my sympathies were now wholly with the pig.",
    "chinese": "就在第一个下午，我便有一种预感：这出戏再也无法恢复平衡，而我的同情现在已经完全转向了那头猪。",
    "hint": "presentiment",
    "note": "?????????"
  },
  {
    "id": "u6-02",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 2,
    "word": "farcical",
    "meaning": "滑稽的；荒唐的",
    "sentence": "I found myself cast suddenly in the role of pig’s friend and physician—a farcical character with an enema bag for a prop.",
    "chinese": "我突然发现自己被安排扮演猪的朋友兼医生这一角色——一个拿灌肠袋当道具的滑稽人物。",
    "hint": "farce",
    "note": ""
  },
  {
    "id": "u6-03",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 3,
    "word": "vigil",
    "meaning": "守夜；看护",
    "sentence": "This was slapstick—the sort of dramatic treatment that instantly appealed to my old dachshund, Fred, who joined the vigil, held the bag, and, when all was over, presided at the internment.",
    "chinese": "这是一出闹剧——这种戏剧性的处理立刻吸引了我的老腊肠犬弗雷德；它加入守夜，帮忙看着袋子，并在一切结束后主持了埋葬。",
    "hint": "vigilant",
    "note": ""
  },
  {
    "id": "u6-04",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 4,
    "word": "desultory",
    "meaning": "散漫的；无计划的",
    "sentence": "I move in a desultory society and often a week or two will roll by without my going to anybody’s house to dinner or anyone’s coming to mine.",
    "chinese": "我生活在一个来往散漫的社交圈里，常常一两个星期过去，我既不去别人家吃饭，也没人来我家。",
    "hint": "desultorily",
    "note": ""
  },
  {
    "id": "u6-05",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 5,
    "word": "revulsion",
    "meaning": "厌恶；反感",
    "sentence": "He not only did not crave food, he felt a positive revulsion to it.",
    "chinese": "他不仅不想吃东西，反而对食物产生了强烈的厌恶。",
    "hint": "revulsive",
    "note": ""
  },
  {
    "id": "u6-06",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 6,
    "word": "vicariously",
    "meaning": "间接感受到地；替代性地",
    "sentence": "The pig’s imbalance becomes the man’s, vicariously, and life seems insecure, displaced, transitory.",
    "chinese": "猪的失调会间接变成人的失调，于是生活显得不安稳、错位而短暂。",
    "hint": "vicarious",
    "note": ""
  },
  {
    "id": "u6-07",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 7,
    "word": "inextricably",
    "meaning": "无法分开地；密不可分地",
    "sentence": "The pig’s lot and mine were inextricably bound now, as though the rubber tube were the silver cord.",
    "chinese": "这头猪的命运和我的命运如今已经密不可分，仿佛那根橡皮管就是把我们连在一起的银色纽带。",
    "hint": "inextricable",
    "note": ""
  },
  {
    "id": "u6-08",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 8,
    "word": "obsession",
    "meaning": "执念；着迷",
    "sentence": "The task of trying to deliver him from his misery became a strong obsession.",
    "chinese": "设法把它从痛苦中解救出来这件事，成了我强烈的执念。",
    "hint": "obsess",
    "note": ""
  },
  {
    "id": "u6-09",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 9,
    "word": "transitory",
    "meaning": "短暂的；转瞬即逝的",
    "sentence": "The pig’s imbalance becomes the man’s, vicariously, and life seems insecure, displaced, transitory.",
    "chinese": "猪的失调会间接变成人的失调，于是生活显得不安稳、错位而短暂。",
    "hint": "transit",
    "note": ""
  },
  {
    "id": "u6-10",
    "unit": "Extra Unit 2",
    "title": "The Death of a Pig",
    "number": 10,
    "word": "dispatch",
    "meaning": "迅速处理；效率",
    "sentence": "But even so, there was a directness and dispatch about animal burial.",
    "chinese": "即便如此，动物的埋葬仍然显得直接而迅速。",
    "hint": "dispatch",
    "note": "???????"
  }
];
